---
- name: BIG-IP AS3
  hosts: lb
  connection: local
  gather_facts: false

  tasks:

  - name: DELETE AS3
    uri:
      url: "https://{{ private_ip }}:{{ mgmt_port }}/mgmt/shared/appsvcs/declare/WorkshopExample"
      method: DELETE
      status_code: 200
      timeout: 300
      body_format: json
      force_basic_auth: yes
      user: "{{ ansible_user }}"
      password: "{{ ansible_pass }}"
      validate_certs: no
    delegate_to: localhost
