---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  
  tasks:
  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      provider:
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_pass}}"
        server_port: "{{mgmt_port}}"
        validate_certs: no
      name: "vip"
      destination: "{{vip}}"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "http_pool"
      snat: "Automap"