---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false

  tasks:
  - name: SAVE RUNNING CONFIG ON BIG-IP
    bigip_config:
      provider:
        server: "{{private_ip}}"
        user: "{{ansible_user}}"
        password: "{{ansible_pass}}"
        server_port: "{{mgmt_port}}"
        validate_certs: no
      save: yes